name: Sync Repos

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        
      - name: Get Branch Name
        id: get_branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Push to Destination Repository
        run: |
          git remote add destination https://github.com/everii-Group/helloHQ-developer-docs.git
          git push destination ${{ env.BRANCH_NAME }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.EVERII_SYNC }}
