name: Sync all branches to another repository

on:
  push:
    branches:
      - main  # Dies ist der Trigger-Branch. Du kannst dies anpassen, um alle Branches zu triggern.

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures all branches and history are fetched

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync All Branches
        env:
          TARGET_REPO_PAT: ${{ secrets.EVERII_SYNC }}
        run: |
          # Remote URL for the target repository
          TARGET_REPO_URL="https://monderino:${{ secrets.EVERII_SYNC }}@github.com/everii-Group/helloHQ-developer-docs.git"
          
          # Fetch all branches
          git fetch --all

          # Iterate over all branches and push them to the target repository
          for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
            echo "Pushing branch $branch to target repository"
            git push --force $TARGET_REPO_URL $branch
          done
          
          # Also push tags
          git push --tags $TARGET_REPO_URL
